CluedIn-io/CluedIn.Connector.SqlServer

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
src/Connector.SqlServer/Features/DefaultBuildCreateIndexFeature.cs
src/Connector.SqlServer/Features/DefaultBuildStoreDataFeature.cs
src/Connector.SqlServer/Features/DefaultFeatureStore.cs
src/Connector.SqlServer/Features/IBuildCreateContainerFeature.cs
src/Connector.SqlServer/Features/IBuildCreateIndexFeature.cs
src/Connector.SqlServer/Features/IBuildStoreDataFeature.cs
test/unit/Connector.SqlServer.Test/Features/DefaultBuildCreateContainerFeatureTests.cs

Adds indexes to generated tables

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
test/integration/Connector.SqlServer.Integration.Tests/Connector.SqlServer.Integration.Tests.csproj
test/integration/Connector.SqlServer.Integration.Tests/SqlServerConnectorTests.cs

Please, don't merge

---

Packages.props
docs/3.2.3-release-notes.md
src/Connector.SqlServer/Connector/BulkSqlClient.cs
src/Connector.SqlServer/Connector/IBulkSqlClient.cs
src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
src/Connector.SqlServer/Features/DefaultBuildCreateIndexFeature.cs
src/Connector.SqlServer/Features/DefaultBuildStoreDataFeature.cs
src/Connector.SqlServer/Features/DefaultBulkStoreDataFeature.cs
src/Connector.SqlServer/Features/DefaultFeatureStore.cs
src/Connector.SqlServer/Features/IBulkStoreDataFeature.cs
src/Connector.SqlServer/InstallComponents.cs
test/integration/Connector.SqlServer.Integration.Tests/Connector.SqlServer.Integration.Tests.csproj
test/integration/Connector.SqlServer.Integration.Tests/SqlServerConnectorTests.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs

Added experimental bulk inserts (WIP) and some other minor fixes

323 performance improvements

---

docs/3.3.0-release-notes.md
src/Connector.SqlServer/Connector/SqlServerConnector.cs

CLR types that do not map to SQL types will be serialized as JSON

---

.github/CODEOWNERS

chore: configure codeowners

---

src/Connector.SqlServer/SqlServerConnectorProvider.cs

Addresses [AB#6966](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/6966)

fix: Ensure schedule and api limit set for provider

---

Packages.props
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/SqlServerConnectorProvider.cs
src/Connector.SqlServer/SqlServerConstants.cs
test/unit/Connector.SqlServer.Test/Connector.SqlServer.Unit.Tests.csproj
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs
test/unit/Connector.SqlServer.Test/SqlServerConnectorProviderTests.cs
test/unit/Connector.SqlServer.Test/TestContext.cs

- chore: Add unit tests based on 3.2.5
- reafactor: Update 3.2.5 tests to compile on latest
- fix: Use local static key names to remove breaking change
- refactor: Update types base on common connector
- fix: Correct tests based on new common connector implementation

fix: Correct casing of config model AB#7136

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

[AB#17622](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/17622)
Add logic for retrying all places where we interact with target.

chore: Add basic retry logic

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

Work item ID: [AB#17804](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/17804)
`VerifyExistingContainer` will be called before tables are even created, so we need to bail out before examining them. Ideally we would not call `VerifyExistingContainer` before tables have been created, but since it happens in platform, we don't have control over that here.

fix: Bail out of VerifyExistingContainer, if tables does not exist

---

Packages.props
src/Connector.SqlServer/Connector/BulkSqlClient.cs
src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Features/DefaultUpgradeTimeStampingFeature.cs
src/Connector.SqlServer/Features/IUpgradeTimeStampingFeature.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs

Work Item ID: [AB#17845](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/17845)
Implement use of transactions. This PR requires: https://github.com/CluedIn-io/CluedIn.Connector.Common/pull/24

feat: Execute commands in transactions

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Features/AddCustomTypesFeature.cs
src/Connector.SqlServer/Features/DefaultFeatureStore.cs
src/Connector.SqlServer/Features/IAddCustomTypesFeature.cs

Work item ID: [AB#18104](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18104)
Add custom types, as part of creating container.

fix: Add custom types when creating container

---

src/Connector.SqlServer/Features/SqlColumnHelper.cs
test/unit/Connector.SqlServer.Test/Features/DefaultBuildCreateContainerFeatureTests.cs

Work item ID: [AB#18149](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18149)

fix: Set nvarchar limit to max

---

docs/3.4.0-release-notes.md

Work item ID: [AB#18144](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18144)
Add release notes for 3.4.0

chore: Add 3.4.0 release notes

---

src/Connector.SqlServer/Connector/SqlClient.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs

Work Item ID: [AB#18332](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18332)
Set the max pool size, as to not run out of connections

fix: Set max pool size to 200

---

docs/3.4.0-release-notes.md
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
src/Connector.SqlServer/Features/DefaultUpgradeTimeStampingFeature.cs
src/Connector.SqlServer/Features/SqlColumnHelper.cs

Work item ID: [AB#18400](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18400)

feat: Allow configuration of default column size

---

Packages.props
src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs

Update reference to common connector, and adapt connector to dispose connections

chore: Update common connector reference

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

Pass all caught exceptions, and the inner exceptions for ConnectorExceptions

chore: Pass caught exceptions as inner exceptions of thrown exceptions

---

Packages.props
docs/3.4.0-release-notes.md
src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Features/AddCustomTypesFeature.cs
src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
src/Connector.SqlServer/Features/DefaultFeatureStore.cs
src/Connector.SqlServer/Features/DefaultUpgradeTimeStampingFeature.cs
src/Connector.SqlServer/Features/IAddCustomTypesFeature.cs
src/Connector.SqlServer/Features/SqlColumnHelper.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs
test/unit/Connector.SqlServer.Test/Features/DefaultBuildCreateContainerFeatureTests.cs

Work Item ID: [AB#18931](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18931)

chore: Merge release/3.4.0 to develop

---

Packages.props

Work Item ID: [AB#18931](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18931)

chore: Update Common connector reference to 3.5.3

---

Packages.props

Work Item ID: [AB#18931](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18931)

chore: Merge release/3.5.3 to develop

---

docs/3.7.0-release-notes.md

Work Item ID: [AB#21242](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/21242)
Add release notes file

chore: Add release notes for 3.7.0

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Exceptions/IncompatibleTableException.cs

Work Item ID: [AB#23562](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23562)
Revert reverts, after testing on platform staging

chore: Reintroduce table verification logic

---

src/Connector.SqlServer/Utils/LatestPersistInfoCommandUtility.cs

Work Item ID: [AB#23558](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23558)
Remove read that was introduced by mistake.

chore: Remove wrong reading of row

---

Packages.props
src/Connector.SqlServer/Connector.SqlServer.csproj
src/Connector.SqlServer/Connector/ConnectionAndTransaction.cs
src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Connector/SqlServerConnectorCommand.cs
src/Connector.SqlServer/CrawlJobDataWrapper.cs
src/Connector.SqlServer/ISqlServerConstants.cs
src/Connector.SqlServer/InstallComponents.cs
src/Connector.SqlServer/SqlServerConnectorComponent.cs
src/Connector.SqlServer/SqlServerConnectorProvider.cs
src/Connector.SqlServer/SqlServerConstants.cs
src/Connector.SqlServer/Utils/StringExtensions.cs
test/unit/Connector.SqlServer.Test/Connector.SqlServer.Unit.Tests.csproj
test/unit/Connector.SqlServer.Test/SqlServerConnectorProviderTests.cs

Work Item ID: [AB#23758](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23758)
Remove dependency on connector common.
Unit tests and manually tested.
chore: Remove dependency on connector common

chore: Remove dependency on connector common

---

Packages.props
docs/4.0.0-release-notes.md
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/RenameTablesUtility.cs

Work Item ID: [AB#30794](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30794)
React to new settings to whether to export edge properties, added in https://github.com/CluedIn-io/CluedIn/pull/5333.

feat: Use option for streaming edge properties

---

docs/4.0.0-release-notes.md
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/RenameTablesUtility.cs
src/Connector.SqlServer/Utils/StringExtensions.cs
test/unit/Connector.SqlServer.Test/Utils/StringExtensionsTests.cs

chore: Merge release to develop

---

README.md

chore: Update the readme file

---

GitVersion.yml

Bump next version explicitly to make sure GitVersion is tracking the version correctly

chore: Bump next GitVersion version

---

docs/4.3.0-release-notes.md

Work Item ID: [AB#37346](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/37346)

docs: added release notes for 4.3.0

---

docs/4.0.1-release-notes.md

Work Item ID: [AB#37578](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/37578)
Add release notes for `4.0.1`
n/a

chore: Add 4.0.1 release notes

---

docs/4.1.1-release-notes.md

chore: Add 4.1.1 release notes

---

docs/4.1.1-release-notes.md
src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/MainTableDefinitionTests.cs

Merge release/4.1.1 to develop

chore: Merge release/4.1.1 to develop

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

Work Item ID: [AB#44065](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/44065)
Improve messages returned, when connection fails to open, or when specified schema is not present.

chore: Improve VerifyConnection error messages

---

docs/4.1.2-release-notes.md

Merge release/4.1.2 to develop

chore: merge release/4.1.2 to develop
