azure-pipelines.yml

Replaces the manual process to authenticate with nuget (which requires updating the nuget key whenever it is out-of-date) with the dedicated task from Azure Pipelines.
Details on the task are here: docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops

fix: automate nuget auth for build

---

docs/3.2.5-release-notes.md
src/Connector.SqlServer/Features/DefaultBuildStoreDataFeature.cs
test/unit/Connector.SqlServer.Test/Features/DefaultBuildStoreDataFeatureTests.cs

Cherry-pick fix from `develop` to format unknown value as JSON. Should work for non-primitive values only (like arrays), as primitives should be mapped to known SQL types.

fix: Ensure parameter value is serialized if unknown type

---

Packages.props

Updated the version of cluedin that it is built against

solves: not showing supported modes correctly in 330 AB#6273

---

Packages.props
src/Connector.SqlServer/SqlServerConstants.cs

For [AB#7136](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/7136)
Forces the config values to use camel Casing at in 3.2.5 and uses friendly display names for the auth control labels

fix: Config requires camelCasing

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

```
[11:57:13 DBG][CluedIn.Connector.SqlServer.Connector.SqlServerConnector] Sql Server Connector - Store Edge Data - Generated query: DELETE FROM [ljuTestStream123Edges] where [OriginEntityCode] = @OriginEntityCode
INSERT INTO [ljuTestStream123Edges] ([OriginEntityCode],[Code]) values
(@OriginEntityCode, @0)
[11:57:13 DBG][CluedIn.Connector.SqlServer.Connector.SqlServerConnector] Sql Server Connector - Store Edge Data - Generated query: DELETE FROM [ljuTestStream123Edges] where [OriginEntityCode] = @OriginEntityCode
```
Add a configuration switch to disable syncing Edges table (DELETE FROM before INSERT INTO); This is per request by SAP in order to reduce the criticality of the impediment to non-blocker and provide a viable workaround.
Due to unknown circumstances, DELETE from is …

workaround: option to disable syncing Edges table

---

src/Connector.SqlServer/Features/SqlColumnHelper.cs
test/unit/Connector.SqlServer.Test/Features/DefaultBuildCreateContainerFeatureTests.cs

Zendesk ticket: https://cluedin.zendesk.com/agent/tickets/579
Partner raising a change request to limit size of nvarchar to improve performance when pulling from SQL server. Seems harmless enough.

chore: Add limit of 1024 to nvarchar field

---

Packages.props

With updated dependency version we can create tables with underscores. Tested and it seems to work!
That's a partial port of PR #46

chore: Update Connector.Common to support underscore in names

---

src/Connector.SqlServer/Features/VerifyUniqueIndexFeature.cs

Work Item ID: [AB#17870](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/17870)
We need to filter on table name, since other tables might have the indexes named the same as the one we're trying to drop.

fix: Filter on table when verifying indexes

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

Work Item ID: [AB#18519](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18519)
We need to copy the datatypes from the model, otherwise we're adding to them, and will have duplicates on retry.

fix: Copy datatypes when creating tables, to avoid duplicates on retry

---

Packages.props

Work item ID: [AB#18931](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/18931)
Update reference to released version

chore: Update common connector reference to 3.4.4

---

src/Connector.SqlServer/Features/AddCustomTypesFeature.cs

Permission to types should be preconfigured for the write user.
There is no need to grant permissions on the created type.
The write user should be granted the following permissions:
```
GRANT CREATE TYPE TO writeUser
GRANT ALTER TO writeUser
GRANT EXECUTE TO writeUser
-- If using a schema name
-- GRANT ALTER ON SCHEMA :: mySchema TO writeUser
-- GRANT EXECUTE ON SCHEMA :: mySchema TO writeUser
```

fix: Remove grants execution on created type

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Exceptions/IncompatibleTableException.cs

Work Item ID: [AB#21250](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/21250)
Throw "nice" exception when old table exists, so that it's easier to identify upgrade needs to happen.
Setup old version of connector, and create stream. Switch to new connector, and observe that exception is thrown.

feat: Throw exception if old table exists

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/MainTableColumnDefinition.cs
src/Connector.SqlServer/Utils/SqlConnectorEntityData.cs
src/Connector.SqlServer/Utils/StoreCommandBuilder.cs
src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs

Work Item ID: [AB#23472](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23472)
Include timestamp in `SqlConnectorEntityData`, to simplify passing

chore: Simplify passing of timestamp

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/MainTableColumnDefinition.cs
src/Connector.SqlServer/Utils/SqlConnectorEntityData.cs
src/Connector.SqlServer/Utils/StoreCommandBuilder.cs
src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs

Work Item ID: [AB#23472](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23472)
Apply #79 on release.
> Include timestamp in SqlConnectorEntityData, to simplify passing

chore: Simplify passing of timestamp [Cherry-pick]

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Exceptions/IncompatibleTableException.cs

Work Item ID: [AB#21250](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/21250)
Apply #78 on develop
> Throw "nice" exception when old table exists, so that it's easier to identify upgrade needs to happen.
>## Test approach 
>Setup old version of connector, and create stream. Switch to new connector, and observe that exception is thrown.

feat: Throw exception if old table exists [Cherry-pick]

---

src/Connector.SqlServer/Utils/TableDefinitions/EdgeTableDefinition.cs

Work Item ID: [AB#23497](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23497)
During testing on Platform staging, deadlocks was occurring. This was due to an unnecessary table scan that was happening in the insert of edges.
Old query plan:
New query plan:
Note: The tables scans that are present in the new query plan, all happen on the custom table typed variables, ie. the tables that are passed as parameters. They should therefore be small and won't have contention with other queries.
Create new stream, exporting incoming and or outgoing edges, and observe that index is added.
In order to performance test, you need to have a sufficiently large dataset (in platform staging, 200K, but smaller will likely suffice), and stream it all at once. Without …

fix: Add index on entity id in edge tables

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs

Work Item ID: [AB#21250](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/21250)
Check if table is present, before doing check of columns.
Log exception instead of throwing, since throwing exception will lock user out of doing anything with the connector.
Exception that is logged:
```
Not all expected columns were present, most likely because the table was created in an old version
CluedIn.Connector.SqlServer.Exceptions.IncompatibleTableException: Table is incompatible:
StreamId: 0e63668d-0bde-4394-b204-85f98fc16e4d
ConnectorProviderDefinitionId: 81314218-1f77-48fe-95c2-d9fb7120519d
It looks like the tables in the database is not compatible with this version of the connector.
This is most likely because the tables were created in an older version of …
```

fix: Rework `VerifyExistingContainer`, to log exception if table is incompatible

---

src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/MainTableDefinitionTests.cs

Work Item ID: [AB#23548](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23548)
Filter out default properties from properties that have been selected to be exported. This is so that we don't have the same column twice. Example of property that can be selected to be exported, but is in default columns is `PersistVersion`
Run unit test

fix: Filter out default columns from properties

---

src/Connector.SqlServer/Utils/TableDefinitions/EdgeTableDefinition.cs

Work Item ID: [AB#23551](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23551)
If no edges are present, we can simplify the command that we run to upsert in sync mode.
Simply, we delete all rows, that have the `EntityId` of the entity we're currently syncing.
Manually tested.

chore: Use simpler command for syncing edge data, when none is present

---

src/Connector.SqlServer/Utils/TableDefinitions/CodeTableDefinition.cs
src/Connector.SqlServer/Utils/TableDefinitions/EdgePropertiesTableDefinition.cs
src/Connector.SqlServer/Utils/TableDefinitions/EdgeTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/CodeTableDefinitionTests.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/EdgePropertiesTableDefinitionTests.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/EdgeTableDefinitionTests.cs

Work Item ID: [AB#23629](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23629)
Discovered these mistakes while testing https://github.com/CluedIn-io/CluedIn/pull/4674.
Fixed and added tests
Side notes: Was partially introduced here: https://github.com/CluedIn-io/CluedIn.Connector.SqlServer/pull/77/commits/04467fe3045fcc000310ce280092fd5b475c7aae
Run new unit tests

fix: Set correct column types in event mode

---

src/Connector.SqlServer/Utils/TableDefinitions/EdgePropertiesTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/EdgePropertiesTableDefinitionTests.cs

Work Item ID: [AB#23694](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23694)
Add entity id to edge properties table. This simplifies the queries used for upserting properties, as well as fixes issue where edge property that had been removed in entity, was not removed from export target.
Run new unit test. Manually tested.

chore: Add entity id to edge properties table

---

src/Connector.SqlServer/Connector/SqlClient.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs
test/unit/Connector.SqlServer.Test/TestContext.cs

Work Item ID: [AB#29867](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/29867)
Disable `MultipleActiveResultSets`

chore: Disable multiple active result sets in connection string

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/Upgrade/UpgradeCodeTableUtility.cs
src/Connector.SqlServer/Utils/Upgrade/UpgradeTo370Utility.cs

Work Item ID: [AB#30088](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30088)
Explicitly dispose readers, since after we disabled MARS in #100, we will get an error if we try to commit a transaction, with multiple active readers.
Manually tested, including method specified in [AB#30088](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30088)

fix: Explicitly dispose readers

---

src/Connector.SqlServer/Utils/StringExtensions.cs
test/unit/Connector.SqlServer.Test/Utils/StringExtensionsTests.cs

Work Item ID: [AB#30652](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30652)
Prepend table name with `Table`, if the table name starts with a digit. This is because table names cannot start with digits.
UI:

fix: Prepend table names starting with digit

---

docs/4.0.0-release-notes.md
src/Connector.SqlServer/Utils/StringExtensions.cs
test/unit/Connector.SqlServer.Test/Utils/StringExtensionsTests.cs

Work Item ID: [AB#30770](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30770)
Cap length of column names.
Run stream/new unit test
fix: Cap length of column names. If names are longer than 127 characters, we cut off anything after character 116, and append hash value of the entire name.

fix: Cap length of column name

---

docs/4.0.0-release-notes.md
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/StoreCommandBuilder.cs
src/Connector.SqlServer/Utils/TableDefinitions/CodeTableDefinition.cs
src/Connector.SqlServer/Utils/TableDefinitions/EdgePropertiesTableDefinition.cs
src/Connector.SqlServer/Utils/TableDefinitions/EdgeTableDefinition.cs

Work Item ID: [AB#30895](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30895)
Refactor so that store/delete queries are executed in single command, cutting down on round trips, to improve performance.
Run stream, streaming entities, and merge entities to test delete.
chore: Refactor queries, so that fewer round trips are needed to store entity.

chore: Refactor store queries, to be executed in single command

---

global.json
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/CreateTableCommandUtility.cs
src/Connector.SqlServer/Utils/SqlName.cs
src/Connector.SqlServer/Utils/StringExtensions.cs
src/Connector.SqlServer/Utils/TableNameUtility.cs
test/unit/Connector.SqlServer.Test/Utils/CreateCustomTypeCommandUtilityTests.cs
test/unit/Connector.SqlServer.Test/Utils/StringExtensionsTests.cs
test/unit/Connector.SqlServer.Test/Utils/TableNameUtilityTests.cs

Work Item ID: [AB#30878](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30878)
Set new max of `105` characters for main table names, since SQL has a max name length of `128`, and we need to leave space for 3 things:
- Parameter declaration `@`
- Other table names are created using main table name, and a suffix, the longest of which is `OutgoingEdgeProperties`, which has a length of 22 characters.
- Custom types are created, using tables names, and the suffix of `Type`, which has a length of 4 characters
In summary: `128 - (1 + 22 + 4) = 101`
This does not leave enough space for the full names of all primary key constaints, so if the main table name is fx:
```
TestTableName101CharactersAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
```

fix: Set max of 101 characters for main table name, to leave enough space for suffixes

---

src/Connector.SqlServer/Utils/TableDefinitions/EdgePropertiesTableDefinition.cs

Work Item ID: [AB#30693](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/30693)
Add index on `EntityId` in edge properties table, since we filter on it in multiple queries. Without it, we have a queryplan like this:
With the index, the query plan for the same query looks like this:
The table scan in the query plan, is of the table we pass as parameter.
Create stream that exports edge properties, observe that indexes are added

chore: Add index for EntityId in edge properties tables

---

src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/MainTableDefinitionTests.cs

Work Item ID: [AB#36302](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/36302)
Add cases for formatting `DateTime` and `DateTimeOffset` properties in ISO8601 format. Add unit tests of this.
Unit tests added.
Manually tested using both versions of platform passing `DateTime` and `DateTimeOffset`.
chore: All `DateTime` and `DateTimeOffset` properties will be formatted in ISO8601 format.

fix: Specifically format DateTimeOffset properties

---

src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/SqlServerConstants.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs

Work Item ID: [AB#37975](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/37975)
Make connection pool size configurable. Also return better error message when port number is configured incorrectly.
Manually tested.
Added unit tests.
feat: Make connection pool size configurable.

feat: Make Connection pool size configurable

---

src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/MainTableDefinitionTests.cs

Work Item ID: [AB#37700](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/37700)
Three things of concern here: 
1. When we sanitize property names for use as column names, we can end up having duplicate names, which causes errors when trying to create main table. To handle this, when creating the names, check if name has already been used, and if so, add number at the end.
2. Order properties in the main table. This ensure that duplicate names, will always represent the same underlying property
3. Don't return sanitized name in `GetValidMappingDestinationPropertyName`. Since this method only takes one name at a time, we cannot add numbers to the end of duplicated names. If we return the sanitized name here, any properties with duplicated names when …

fix: Handle vocabulary property names being sanitized to the same names

---

docs/4.1.1-release-notes.md
src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/MainTableDefinitionTests.cs

Work Item ID: [AB#43258](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/43258)
Add case for manually serializing entity type values. Without this, export will fail, since SqlClient can't serialize EntityType.
Manually and added unit tests.
fix: Fix issue where entity type properties were not serialized correctly, leading storing data to fail

fix: Add case for manually serializing entity type values

---

src/Connector.SqlServer/Connector/ISqlClient.cs
src/Connector.SqlServer/Connector/SqlClient.cs
src/Connector.SqlServer/Connector/SqlServerConnector.cs
src/Connector.SqlServer/Utils/ConnectorConnectionExtensions.cs

Work Item ID: [AB#43949](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/43949), [AB#43956](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/43956)
2 parts:
- Add verification of schema in `VerifyConnection`. This will cause test connection to fail in UI, and export target to become unhealthy is incorrect schema is specified.
- Fix issue where if empty string was specified as schema, we would not fallback to default.
Manually by specifying empty schema, incorrect schema and correct schema, and streaming entity
Fix issue where incorrectly specified schema results in entity not being streamed

fix: Validate schema correctly, and fallback to default if empty string is specified

---

src/Connector.SqlServer/Connector/SqlClient.cs
test/unit/Connector.SqlServer.Test/Connector/SqlClientTests.cs

Work Item ID: [AB#44188](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/44188)
Turn off encryption requirement, as now it's required by default
Tested manually
Disable encryption requirement and verification to support update of SqlClient library

chore: Turn off connection encryption requirement

---

src/Connector.SqlServer/Utils/TableDefinitions/MainTableDefinition.cs
test/unit/Connector.SqlServer.Test/Utils/TableDefinitions/MainTableDefinitionTests.cs

Work Item ID: [AB#44676](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/44676)
Add case for converting `PersonReference` typed properties.
Manually tested and added unit test
Fixes issue where entities with person references (such as those coming from manual data entry) will not be streamed.

fix: Convert PersonReference typed properties

---

Packages.props
src/Connector.SqlServer/Connector/SqlClient.cs

Work Item ID: [AB#44188](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/44188)
Update platform dependency to latest 4.5.0.
It's needed because platform updated SQL Server client lib and it has a binary breaking change.
Tested manually
Update platform dependency to 4.5.0

chore: Update platform dependency to 4.5.0
